### ISSUE TITLE
Adding external (bank) account to account using hash of values fails 

### ISSUE THREAD

**Issue by leoht** [stripe/stripe-mock#187] opened 2019-11-06 12:14 UTC
It seems like the mock validation of the field `external_account` for this endpoint:
https://stripe.com/docs/api/external_account_bank_accounts/create?lang=curl

isn't aligned with the test/live API:

This curl calling the test API is successfully creating the external account object:
```
curl https://api.stripe.com/v1/accounts/{account_id}/external_accounts   -u sk_test_{hidden}:   -d 'external_account[object]=bank_account&external_account[account_number]=DE89370400440532013000&external_account[currency]=EUR&external_account[country]=DE'
```

But the same call against the mock fails using a map of values instead of a string token for `extenral_account`:
```
curl http://localhost:12111/v1/accounts/{account_id}/external_accounts   -u sk_test_{hidden}:   -d 'external_account[object]=bank_account&external_account[account_number]=DE89370400440532013000&external_account[currency]=EUR&external_account[country]=DE'
```
Response from mock:
```
'
{
  "error": {
    "message": "Request validation error: validator 0xc420e7ebd0 failed: object property 'external_account' validation failed: value is not a string (Kind: map)",
    "type": "invalid_request_error"
  }
}
```

**Comment by bdtomlin** [comment] 2021-03-04 21:08
@leoht, thanks for opening this. I'm running into the same issue. I have to temporarily skip some tests until this is resolved.

**Comment by fredwu** [comment] 2021-06-01 12:22
This issue still persists... ;( Anyone from Stripe who might be willing to take a look please? 🙏  cc @richardm-stripe @remi-stripe

**Comment by remi-stripe** [comment] 2021-06-01 15:26
Hey everyone! stripe-mock doesn't support every option our API does today and this is one of the features that it just rejects for now. We recommend really mocking the call in your code instead of using stripe-mock if that's the approach you're taking in your code.
Relatedly, we recommend creating a bank account token client-side with the IBAN element for this as documented [here](https://stripe.com/docs/js/tokens_sources/create_token?type=ibanElement) and then passing that `btok_123` to the API instead.

**Comment by pakrym-stripe** [comment] 2023-01-17 21:18
Related: [External Account should support an object](https://github.com/stripe/openapi/issues/49)

**Comment by richardm-stripe** [comment] 2023-07-19 17:48
Closing as we don't intend to take any action here. Flows with raw details are slightly more frictionful by design.

**Closed by richardm-stripe** 2023-07-19 17:48 UTC
