### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by bradobro** [stripe/stripe-mock#26] opened 2017-10-24 20:28 UTC
Hey Stripe, 

We're going to find this very useful. We need to do a few custom things on a fork. 

I'm getting a lot of failures on `make test`:

```
go test ./...
--- FAIL: TestValidFixtures (0.12s)
    --- FAIL: TestValidFixtures/source (0.00s)
        Error Trace:    8:
    	Error:		No error is expected but got validator 0xc4208e4570 failed: object property 'bitcoin' validation failed: object property 'refund_address' is required

--- FAIL: TestResourcesCanBeGenerated (0.57s)
    --- FAIL: TestResourcesCanBeGenerated/get_/v1/sources/{source}_(without_expansions) (0.00s)
    	generator_test.go:207: Schema is: {
    		  "$ref": "#/components/schemas/source"
```

I'm glad to PR the fix if you advise me how you want it.

**Comment by brandur-stripe** [comment] 2017-10-25 12:12
Thanks for reporting Brad! Our bad for not noticing this sooner.

@tmaxwell-stripe Most of the failures seem to be related to briging in sources. Do you know if we ended up generating equivalently valid fixtures for the new sources detail that we brought in?

**Comment by bradobro** [comment] 2017-10-25 13:55
I don't @brandur-stripe--unfortunately, we're behind on our Stripe API versions. We're hoping to use stripe-mock to help us make those transitions a bit less frightening!

You can see some of the gyrations we're taking on our fork, [kindrid/stripe-mock](https://github.com/kindrid/stripe-mock).

**Comment by tmaxwell-stripe** [comment] 2017-10-25 16:47
The `object property 'refund_address' is required` failures seems to be caused by an error in the OpenAPI spec; that field shouldn't actually be marked as required. (We have an internal script that generates the spec, so we'll need to update the script to correctly calculate which fields are required.)

**Comment by brandur-stripe** [comment] 2017-10-25 19:35
> I don't @brandur-stripe--unfortunately, we're behind on our Stripe API versions. We're hoping to use stripe-mock to help us make those transitions a bit less frightening!

@bradobro Ah no problem! I was asking Tim here — he's been working on this recently and would have the best idea on how to proceed.

> You can see some of the gyrations we're taking on our fork, kindrid/stripe-mock (escrowed old versions, lean Alpine Docker image).

Nice! We're hoping to find some new users here, so definitely looking forward to supporting you how we can.

> The object property 'refund_address' is required failures seems to be caused by an error in the OpenAPI spec; that field shouldn't actually be marked as required. (We have an internal script that generates the spec, so we'll need to update the script to correctly calculate which fields are required.)

@tmaxwell-stripe Thanks! Do you think this would be a small enough fix that you could plausibly take a stab during run this week? It'd be nice to get stripe-mock's test suite back to a point where it's stable.

**Comment by bradobro** [comment] 2017-10-25 19:48
Great @tmaxwell-stripe. Any chance you can generate OpenAPI specs for the major versions back to 2015-10-16?

**Comment by brandur-stripe** [comment] 2017-10-25 19:49
> Any chance you can generate OpenAPI specs for the major versions back to 2015-10-16?

We've been playing with this idea and how it might be possible, but we don't have great infrastructure for it right now. I think it's doable, but unlikely to be prioritized anytime soon. Sorry!

**Comment by bradobro** [comment] 2017-10-25 19:52
I get it @brandur-stripe. Thanks. We often have to give the same answer.

**Closed** 2017-10-27 23:13 UTC

**Comment by brandur-stripe** [comment] 2017-10-27 23:16
@tmaxwell-stripe's kindly fixed this one and the test suite should be green once again. Let us know if you run into any more trouble! Thanks.
