### ISSUE TITLE
App State

### ISSUE THREAD

**Issue by JackWink** [stripe/stripe-mock#19] opened 2017-09-14 16:12 UTC
Curious if there are any plans to implement some form of state in stripe-mock. I tried to switch over to using stripe-mock in our test suite, but had to revert once I realized creating tokens then retrieving them would return different data, i.e. card tokens turned into bank accounts when fetched.

I'd be happy to contribute, but I figure keeping state probably requires some discussion about the design and whether or not it aligns with your roadmap.

**Comment by brandur-stripe** [comment] 2017-09-14 22:47
Hi Jack, great question!

I'd definitely thought about this before — I don't think we'd want to go too far into trying to reproduce the API's behavior, but it does seem like at the very least it would be nice if stripe-mock could remember which IDs it'd generated already (and generate unique IDs for new objects so it's not just the same one everytime) and then be able to look them for subsequent requests.

It'll take a fair bit of work to put in. As it stands stripe-mock is pretty unintelligent in that requests are almost entirely decoupled from responses. As long as a request was valid, some response data will be returned, but it'll almost certainly have no relation whatsoever to what the user asked for. There might be a few places where we should at least try to select the right return type as starter (polymorphic resources like cards versus. bank accounts like you mentioned).

cc @tmaxwell-stripe @stripe/api-libraries for interest.

**Comment by mikker** [comment] 2017-10-12 22:21
Could probably also return easily copyable attributes like `amount` from the request to the response.

Of course, as soon as you step into not being completely ignorant in what you return you get into a weird grey area of where to draw the line between what's remembered and what isn't.

**Comment by RobertLowe** [comment] 2017-10-22 16:24
Yea, this is kind of useless for black box testing in our apps without some degree of persistence (in memory is probably fine). It's not reasonable to use static fixtures. It's also a bit difficult to rely on a single testing key as our devs and environments would each need a fictitious stripe account for unique secret keys as not to clash (which is probably what we'll consider). 

Additionally while testing our apps we could record interactions (nock, vcr, etc) or mock expectations, this is less acceptable while running in development where things are less expected. Ideally a mocked out/blackboxed API would be a solution to both cases.

In terms of compatibility would you consider running your production tests against the mock API, as to have 1-to-1 compatibility, not that you would need to release your testing code, I would hope you could run them against this.

This is all a nice to have, but just thought I would provide some feedback. 

I may just hack together a pass-through proxy, which will record and replay like `nock` `vcr` etc, for now we'll just use multiple keys and hope things aren't brittle.

**Comment by brandur-stripe** [comment] 2017-10-23 15:06
I agree that stripe-mock doesn't have sufficient intelligence today, but I'm also wary of swinging too far the other way. If we try to produce something that behaves comparably to the real API we run the risk of it being subtilely incompatible to the point where people can largely rely on it in testing, but then deploy their code and see that it doesn't work in some unexpected way.

There's always going to be varying tiers of testing fidelity with the lowest being tests against preconfigured responses with something like webmock all the way up to using Stripe's testmode which lives in the same service as the real API and behaves almost identically. stripe-mock aims to be somewhere midway up: requests and endpoints are validated, but with minimal domain knowledge.

Again though, I'm in favor of some kind of persistence mode so that you could at least create an entity like a customer and then do something useful with it like reusing the ID to create a charge. We'll implement this as some point.

**Comment by RobertLowe** [comment] 2017-10-23 15:43
I'll make another suggestion, it would be useful if you could manage multiple test environment keys under the live test mode. And additionally perhaps an API call to reset test data.

Cheers, thanks. 👍

**Comment by brandur-stripe** [comment] 2017-10-23 17:29
> I'll make another suggestion, it would be useful if you could manage multiple test environment keys under the live test mode. And additionally perhaps an API call to reset test data.

Yeah, coincidentally we had a conversation about this very recently. Unfortunately resetting test data is unlikely anytime soon — unfortunately removing test data is complicated to implement well. We could make it fine for small accounts, but accounts with large data sets are really problematic for our implementation (you can observe this today if you try to delete data via the Dashboard page and you have a lot of it).

Individual test keys that run in their own sandboxes is something we think is a really good idea though. We've got a few other priorities going and are unlikely to get to this soon, but I'd love to implement it.

**Comment by adrienverge** [comment] 2018-03-18 14:21
If you need a stateful Stripe sandbox, you could also try [localstripe](https://github.com/adrienverge/localstripe). Unlike stripe-mock, not all routes are implemented but those that are actually save data.

This means the "card tokens turned into payment sources" use-case described by @JackWink works there.

**Comment by lowlyocean** [comment] 2020-12-01 03:21
Is there any update on statefulness? (localstripe)[https://github.com/adrienverge/localstripe] is stateful, but noticing when using it in E2E testing that returns 400 errors whenever stripe-python is used with an API parameter that isn't explicitly enumerated in localstripe. Seems a first-party mocking would be the most reliable way to run E2E tests for SaaS

**Comment by remi-stripe** [comment] 2020-12-01 03:38
@mikker No short term plans for a stateful stripe-mock for now unfortunately. We are working on the ability to playback requests though which should help with test suites! No timeline just yet but we're working on this!

**Comment by mikker** [comment] 2020-12-01 13:03
Thanks for the update, but I think you meant to at @lowlyocean ?

**Comment by remi-stripe** [comment] 2020-12-01 16:24
Ah yes, sorry for the mixup :(

**Comment by lowlyocean** [comment] 2020-12-02 04:17
@remi-stripe if I understand what's meant by playback requests, this would mean some initial responses to a series of requests (e.g. during full E2E run) would need to be recorded from a real Stripe server. Then in future E2E runs, these canned responses would be sent. Is this correct? if so it presents at least 3 challenges:

1. There's no way to do initial recording without a hitting a live server (i.e. using particular Stripe account's test keys).
2.  The canned responses need to be stored somewhere the CI/CD can access them.
3. Any change to the test suite that changes the requests will mean a re-recording must be done (and new results must be stored).

**Comment by remi-stripe** [comment] 2020-12-03 02:20
@lowlyocean This will be built within our Stripe CLI tool: https://stripe.com/docs/stripe-cli so that's how you would access this in CI/CD in that case.

I agree it might not fit all use-cases but between this and a real mock (not stripe-mock) it should cover most of what you need in that case.

**Comment by driesvints** [comment] 2020-12-03 09:43
@remi-stripe if you need a beta tester for it let me know. Our test suite for https://github.com/laravel/cashier-stripe is constantly failing now because of rate limiting and I'm desperately looking for solutions without having to result to creating multiple Stripe test keys for different parts of the test suite.

**Comment by utako** [comment] 2021-01-14 01:00
hi @remi-stripe , is this playback feature available yet? would love to also be a beta tester.

**Comment by remi-stripe** [comment] 2021-01-15 23:55
We're still working on it and it is at least a few weeks away from even a rough private beta. But I've flagged your interest to the engineers working on that feature!

**Comment by thrau** [comment] 2021-08-11 09:27
Any update on the progress of this feature? Would be immensely helpful for our test suite.

**Comment by AdrienBr** [comment] 2021-09-24 08:19
Also interested here with statefulness ! It would be a great feature for our automated tests.

**Comment by edalzell** [comment] 2022-03-10 17:51
> My advice for now is to mock the requests yourself when you require state instead.

@remi-stripe are there any good examples of this?

**Comment by alextween** [comment] 2022-09-21 22:12
Reupping this issue: Stripe Mock statefulness would be great.  An answer [to @edalzell 's question](https://github.com/stripe/stripe-mock/issues/19#issuecomment-1064334939) would be great too.

**Comment by tristanoneil** [comment] 2022-09-21 23:34
I was doing some sleuthing because I'm also _very_ interested in what's next for Stripe testing and I found https://github.com/stripe/stripe-cli/pull/537 and then more recently https://github.com/stripe/stripe-cli/pull/925. It seems like as @remi-stripe mentioned something is in the works for supporting Stripe request playback.

**Comment by anniel-stripe** [comment] 2023-01-24 22:52
Hello, sorry for keeping everyone hanging here! Unfortunately, we'll be closing this issue as out of scope. The scope of stripe-mock has been narrowed significantly since its inception in 2017, and we do not have plans to expand its functionality past that of a basic validation tool, which also means we don't have plans to add statefulness. We've updated [the README](https://github.com/stripe/stripe-mock#future-plans) to explain this.

If you have more questions or concerns, please feel free to open a new Github issue!

**Closed by anniel-stripe** 2023-01-24 22:52 UTC
Labels: future
