### ISSUE TITLE
Is there ability in stripe-mock to return mock data instead of empty structs?

### ISSUE THREAD

**Issue by kerak19** [stripe/stripe-mock#48] opened 2018-03-13 12:52 UTC
As the title says, i'm looking for way to use stripe-mock in our application, but for now most of my calls panics or returns error because it gets empty struct and nil pointers.

Is there ability in stripe-mock to return mock data instead of empty structs?

**Comment by brandur-stripe** [comment] 2018-03-13 23:52
Hi @kerak19, `stripe-mock` should have mock fixture data for most common resource types, but doesn't yet have an implementation to return synthesized data for resources that it's not familiar with (although I hope to get to it soon). See #46 where we're tracking that one.

**Comment by kerak19** [comment] 2018-03-14 07:16
Hey @brandur-stripe, thanks for your response.

You see, when, for example, i'm creating credit card using stripe-mock, this is the response:

```
2018/03/14 08:12:12 Requesting POST localhost:12111/v1//customers/need_set_up/cards
&stripe.Card{
  Address1: "",
  Address1Check: "",
  Address2: "",
  Brand: "",
  CVCCheck: "",
  CardCountry: "",
  City: "",
  Country: "",
  Currency: "",
  Customer: nil,
  Default: false,
  Deleted: false,
  Description: "",
  DynLastFour: "",
  Fingerprint: "",
  Funding: "",
  ID: "",
  IIN: "",
  Issuer: "",
  LastFour: "",
  Meta: map[string]string{
  },
  Month: 0,
  Name: "",
  Recipient: nil,
  State: "",
  ThreeDSecure: nil,
  TokenizationMethod: "",
  Year: 0,
  Zip: "",
  ZipCheck: "",
} 
```

Which totally doesn't work for me, because of empty lastFour and Brand fields.

Is that response correct or should there be some data?

Thanks.

**Comment by brandur-stripe** [comment] 2018-03-14 17:30
Yes, sorry about the trouble. The problem is that `stripe-mock` isn't doing a good job of handling "polymorphic" resources like sources and it only has a single fixture that it uses for all of them. The one that's bundled right now is a bank account:

```
$ curl -X POST -H "Authorization: Bearer sk_test_123" http://localhost:12111/v1/customers/need_set_up/cards -d 'source=tok_123'
{
  "account": "acct_1BoJ2AKrZ43eBVAb",
  "account_holder_name": "Jane Austen",
  "account_holder_type": "individual",
  "bank_name": "STRIPE TEST BANK",
  "country": "US",
  "currency": "usd",
  "fingerprint": "VRz2HBgjXYD9uwfT",
  "id": "ba_1BoJ2NKrZ43eBVAbVj8G6hzK",
  "last4": "6789",
  "metadata": {},
  "object": "bank_account",
  "routing_number": "110000000",
  "status": "new"
}
```

So when `stripe-go` tries to deserialize it back to a card, all the fields look empty.

**Comment by adrienverge** [comment] 2018-03-18 14:24
Like for #19: while waiting for the official stripe-mock to save current state, you could use [localstripe](https://github.com/adrienverge/localstripe): it saves data from requests and returns real objects (with `last4` and everything).

**Comment by kerak19** [comment] 2018-03-19 09:32
@adrienverge Thanks, i'll check it out

**Comment by anniel-stripe** [comment] 2023-01-25 19:42
Hello, sorry for the delayed update to this issue! Similar to https://github.com/stripe/stripe-mock/issues/19, I'm closing this issue out as out of scope, since we do not plan to expand stripe-mock functionality past that of a basic sanity check tool. You can refer to [our updated README](https://github.com/stripe/stripe-mock#future-plans), which details our future plans for stripe-mock.

**Closed by anniel-stripe** 2023-01-25 19:42 UTC
