### ISSUE TITLE
Is this up to date with Stripe API ?

### ISSUE THREAD

**Issue by CharlyPoppins** [stripe/stripe-mock#366] opened 2022-10-21 17:11 UTC
Hello,

I'm having this message when trying to create a payment intent :
```Got unexpected keys in options array: amount, currency, payment_method_types, application_fee_amount, description, transfer_data, metadata, payment_method, confirm"}```

This statement seems wrong according to the API : `https://stripe.com/docs/api/payment_intents/create`

Also it's working with Stripe API

**Comment by remi-stripe** [comment] 2022-10-21 17:16
stripe-mock is up to date with our API yes. The error message looks like you're passing parameters in the wrong hash/array in your code and they act as options. Can you share some exact code to reproduce what you're experiencing?

**Comment by CharlyPoppins** [comment] 2022-10-21 19:25
@remi-stripe you're right, I'm trying to mock https://github.com/stripe/stripe-php and I'm doing something wrong.

I had mixed up `Stripe\HttpClient\ClientInterface` and `Stripe\StripeClientInterface`, thanks to your comment it now obvious :)

```
use Stripe\HttpClient\ClientInterface;
use Stripe\StripeClient;
use Stripe\StripeClientInterface;

//class MockStripeClient extends StripeClient implements ClientInterface
class MockStripeClient extends StripeClient implements StripeClientInterface
{
    public function __construct()
    {
        parent::__construct([
                                'api_key' => $_ENV['APP_STRIPE_API_KEY'],
                                'api_base' => 'stripemock:12112',
                            ]);
    }

    public function request($method, $path, $params, $opts)
    {
        dump($method);
        dump($path);
        dump($params);
        dump($opts);

        return parent::request($method, $path, $params, $opts);
    }
```

I'll keep on investigating with `Stripe\ApiRequestor`

**Comment by CharlyPoppins** [comment] 2022-10-21 20:13
I was looking too far...

```
// 
in my test class
protected function setUp(): void
{
        Stripe::$apiBase = $_ENV["APP_STRIPE_MOCK_URL"];
        $curl = new CurlClient([CURLOPT_SSL_VERIFYPEER => 0]);
        ApiRequestor::setHttpClient($curl);
}
```

**Comment by remi-stripe** [comment] 2022-10-21 21:26
Gotcha, glad you figured it out! I'm closing as resolved but let me know if you need help with anything else!

**Closed by remi-stripe** 2022-10-21 21:26 UTC
