### ISSUE TITLE
Fixture for /customer/:customer_id/sources endpoint

### ISSUE THREAD

**Issue by jamesjia94** [stripe/stripe-mock#156] opened 2019-04-05 23:18 UTC
Which resource should I be editing in order to modify the returned response from ` /customer/:customer_id/sources`?

Not sure if this is specific to [stripe-go](https://github.com/stripe/stripe-go), but I'm trying to annotate the paymentsource with a [source object](https://github.com/stripe/stripe-go/blob/69a486ccb431be85b15bb8db02a11738dbeff23a/paymentsource.go#L95), and I can't seem to figure out how to do so.

**Comment by brandur-stripe** [comment] 2019-04-08 14:05
Hey @jamesjia94, sorry about the trouble here, but this is currently a limitation in stripe-mock — when dealing with a polymorphic response, it always returns a fixed fixture regardless of the input parameters.

This is one that we'd love to fix though, as it's going to be a very fundamental limitation for most users. No promises, but I want to spend some time on stripe-mock this week, and I'll start investigating as to whether there's something relatively easy for us to do to support this.

Going to close as duplicate of #36.

**Closed by brandur-stripe** 2019-04-08 14:05 UTC
